version: '3.4'

services:
  rdp_ebd_man_webapi:
    image: ${DOCKER_REGISTRY-}rdpedbmanagementwebapi
    container_name: rdp_ebd_man_webapi
    networks:
        - edb-management-network
    build:
      context: .
      dockerfile: src/RDP.EDB.Management.WebApi/Dockerfile
    env_file:
      - env/.env-webapp
    depends_on:
      - rdp_ebd_man_database
  
  rdp_ebd_man_database:
    image: postgres:alpine3.18
    container_name: rdp_ebd_man_database
    env_file:
      - env/.env-postgresql
    ports:
      - "5432:5432"
    networks:
        - edb-management-network
    volumes:
        - db_volume:/var/lib/postgresql/data
  
networks:
  edb-management-network:

volumes:
  db_volume:
    name: ebd_db_volume
    driver: local  
