name: SonarCloud

on:
  push: 
    branches: ["main"]
    paths-ignore: 
    - README.md

  pull_request:
    branches: ["main", "develop"]

jobs:
  build:

    runs-on: windows-latest

    #iterate?
    
